# @package _group_
task:
  _name: translation_lev
  data: /content/drive/My Drive/Colab Notebooks/Mini-project/iwslt14.tokenized.de-en # path to data directory
  source_lang: de
  target_lang: en
  noise: random_mask
criterion:
  _name: custom_loss
model:
  _name: cmlm_transformer_base
  share_decoder_input_output_embed: true
  decoder:
    learned_pos: true
  encoder:
    learned_pos: true
  dropout: 0.2
  label_smoothing: 0.1
  length_loss_factor: 0.01
optimizer:
  _name: adam
  adam_betas: (0.9,0.999)
lr_scheduler:
  _name: inverse_sqrt
  warmup_updates: 1
  warmup_init_lr: 0.0001
dataset:
  max_tokens: 8192
  validate_interval_updates: 100
optimization:
  lr: [0.0001]
  update_freq: [8]
  max_update: 2000
  stop_min_lr: 1e-09
checkpoint:
  no_epoch_checkpoints: true
  restore_file: './checkpoint_best.pt'
  reset_optimizer: True
  save_dir: './checkpoints'
  save_interval_updates: 10
common:
  log_format: simple
  log_interval: 20
  wandb_project: nlp2_proj1